[package]
name = "ospf-rust-base"
version = "0.1.0"
authors = ["fuookami <wfuookami@gmail.com>"]
edition = "2021"
description = "Base definition for ospf-rust."
license = "Apache-2.0"

homepage = "https://github.com/fuookami/ospf-rust"
repository = "https://github.com/fuookami/ospf-rust"
readme = "../README.md"

[dependencies]
strum = { version = "0.26.3", features = ["derive"] }
paste = "1.0.15"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
