[package]
name = "sfa-opf-rust-minimum"
version = "0.1.0"
authors = ["李伟文 <liweiwen@sf-express.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concat-idents = "*"
libc = "*"
