[package]
name = "ospf-rust-framework-bpp2d"
version = "0.1.0"
authors = ["fuookami <wfuookami@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

homepage = "https://github.com/fuookami/ospf-rust"
repository = "https://github.com/fuookami/ospf-rust"
readme = "../README.md"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
