[package]
name = "ospf-rust-framework-bpp3d"
version = "0.1.0"
edition = "2024"
description = "Operations research modeling framework - BPP3D domain module"
authors = ["fuookami <wfuookami@gmail.com>"]
license.workspace = true

[features]
default = []
serde = ["dep:csv", "dep:serde", "dep:serde_json", "ospf-rust-framework/serde"]
async = ["ospf-rust-framework/async"]
nightly = ["ospf-rust-framework/nightly"]
big-rational = ["ospf-rust-framework/big-rational"]
big-decimal = ["ospf-rust-framework/big-decimal"]
gurobi10 = ["ospf-rust-framework/gurobi10"]
gurobi11 = ["ospf-rust-framework/gurobi11"]
gurobi12 = ["ospf-rust-framework/gurobi12"]
scip = ["ospf-rust-framework/scip"]
scip-bundled = ["ospf-rust-framework/scip-bundled"]
scip-from-source = ["ospf-rust-framework/scip-from-source"]
scip-quadratic = ["ospf-rust-framework/scip-quadratic"]
serde_json = ["dep:serde_json"]

[dependencies]
ospf-rust-base = { path = "../ospf-rust-base" }
ospf-rust-math = { path = "../ospf-rust-math" }
ospf-rust-multiarray = { path = "../ospf-rust-multiarray" }
ospf-rust-quantities = { path = "../ospf-rust-quantities" }
ospf-rust-core = { path = "../ospf-rust-core" }
ospf-rust-framework = { path = "../ospf-rust-framework" }

serde = { version = "1", features = ["derive"], optional = true }
csv = { version = "1.4.0", optional = true }
thiserror = "1"
log = "0.4"
num-traits = "0.2.19"
serde_json = { version = "1.0.150", optional = true }

[dev-dependencies]
ospf-rust-framework = { path = "../ospf-rust-framework" }
