[package]
name = "ospf-rust-example"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []
backend-gurobi = ["ospf-rust-core/gurobi10", "ospf-rust-framework/gurobi10"]

[dependencies]
ospf-rust-core = { path = "../ospf-rust-core" }
ospf-rust-framework = { path = "../ospf-rust-framework" }
ospf-rust-base = { path = "../ospf-rust-base" }
ospf-rust-math = { path = "../ospf-rust-math" }
ospf-rust-multiarray = { path = "../ospf-rust-multiarray" }
