-- Remote Solver core schema baseline. / Remote Solver 核心表基线脚本。
-- Target: PostgreSQL/H2 compatibility. / 目标：兼容 PostgreSQL 与 H2。

CREATE TABLE IF NOT EXISTS remote_solver_migration_history (
    version VARCHAR(32) PRIMARY KEY,
    description TEXT NOT NULL,
    applied_at_epoch_ms BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS remote_solver_task_state (
    task_id VARCHAR(256) PRIMARY KEY,
    request_id VARCHAR(256) NOT NULL UNIQUE,
    status VARCHAR(64) NOT NULL,
    complexity VARCHAR(64) NOT NULL,
    time_sensitivity VARCHAR(64) NOT NULL,
    priority INT NOT NULL,
    deadline_epoch_ms BIGINT NULL,
    payload_model_path TEXT NOT NULL,
    payload_model_version TEXT NULL,
    payload_model_format TEXT NULL,
    payload_config_path TEXT NULL,
    payload_config_version TEXT NULL,
    payload_snapshot_path TEXT NULL,
    payload_snapshot_version TEXT NULL,
    payload_task_meta_solver_type TEXT NULL,
    payload_task_meta_target_type TEXT NULL,
    payload_task_meta_time_limit_ms BIGINT NULL,
    payload_task_meta_solution_limit INT NULL,
    payload_task_meta_estimated_variable_count INT NULL,
    payload_task_meta_estimated_constraint_count INT NULL,
    payload_task_meta_historical_runtime_ms BIGINT NULL,
    payload_task_meta_metadata TEXT NOT NULL,
    payload_extension TEXT NOT NULL,
    has_latest_result BOOLEAN NOT NULL,
    latest_result_feasible BOOLEAN NULL,
    latest_result_optimal BOOLEAN NULL,
    latest_result_objective_value DOUBLE PRECISION NULL,
    latest_result_gap DOUBLE PRECISION NULL,
    latest_result_elapsed_ms BIGINT NULL,
    latest_result_checkpoint_path TEXT NULL,
    latest_result_checkpoint_version TEXT NULL,
    latest_result_result_path TEXT NULL,
    latest_result_result_version TEXT NULL,
    latest_result_message TEXT NULL,
    latest_result_extension TEXT NOT NULL,
    latest_result_report_json TEXT NULL,
    latest_snapshot_path TEXT NULL,
    latest_snapshot_version TEXT NULL,
    assigned_node_id VARCHAR(256) NULL,
    created_at_epoch_ms BIGINT NOT NULL,
    updated_at_epoch_ms BIGINT NOT NULL,
    budget_scope VARCHAR(256) NOT NULL,
    budget_limit DOUBLE PRECISION NULL,
    consumed_cost DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_remote_solver_task_state_queue
    ON remote_solver_task_state (status, priority DESC, created_at_epoch_ms ASC);

CREATE TABLE IF NOT EXISTS remote_solver_slice_state (
    created_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slice_id VARCHAR(256) PRIMARY KEY,
    task_id VARCHAR(256) NOT NULL,
    dispatch_id VARCHAR(256) NOT NULL,
    status VARCHAR(64) NOT NULL,
    node_id VARCHAR(256) NULL,
    quantum_ms BIGINT NOT NULL,
    checkpoint_path TEXT NULL,
    checkpoint_version TEXT NULL,
    result_path TEXT NULL,
    result_version TEXT NULL,
    started_at_epoch_ms BIGINT NULL,
    finished_at_epoch_ms BIGINT NULL,
    error_message TEXT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_remote_solver_slice_state_task_dispatch
    ON remote_solver_slice_state (task_id, dispatch_id);

CREATE INDEX IF NOT EXISTS idx_remote_solver_slice_state_task
    ON remote_solver_slice_state (task_id);

CREATE TABLE IF NOT EXISTS remote_solver_cost_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(256) NOT NULL,
    budget_scope VARCHAR(256) NOT NULL,
    slice_id VARCHAR(256) NOT NULL,
    node_id VARCHAR(256) NOT NULL,
    runtime_ms BIGINT NOT NULL,
    billed_seconds BIGINT NOT NULL,
    price_per_second DOUBLE PRECISION NOT NULL,
    license_cost DOUBLE PRECISION NOT NULL,
    total_cost DOUBLE PRECISION NOT NULL,
    created_at_epoch_ms BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_remote_solver_cost_ledger_task
    ON remote_solver_cost_ledger (task_id, created_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_remote_solver_cost_ledger_scope
    ON remote_solver_cost_ledger (budget_scope, created_at_epoch_ms);

DELETE FROM remote_solver_migration_history WHERE version = '1';
INSERT INTO remote_solver_migration_history(version, description, applied_at_epoch_ms)
VALUES ('1', 'remote_solver_core', 0);
