[package]
name = "ospf-rust-framework-gantt-scheduling"
version = "0.1.0"
edition = "2024"
description = "Operations research modeling framework - Gantt scheduling domain module"
authors = ["fuookami <wfuookami@gmail.com>"]
license.workspace = true

[features]
default = []
serde = ["dep:serde", "ospf-rust-framework/serde", "time/serde"]
async = ["ospf-rust-framework/async"]
nightly = ["ospf-rust-framework/nightly"]
big-rational = ["ospf-rust-framework/big-rational"]
big-decimal = ["ospf-rust-framework/big-decimal"]
gurobi10 = ["ospf-rust-framework/gurobi10"]
gurobi11 = ["ospf-rust-framework/gurobi11"]
gurobi12 = ["ospf-rust-framework/gurobi12"]
scip = ["ospf-rust-framework/scip"]
scip-bundled = ["ospf-rust-framework/scip-bundled"]
scip-from-source = ["ospf-rust-framework/scip-from-source"]
scip-quadratic = ["ospf-rust-framework/scip-quadratic"]

[dependencies]
ospf-rust-base = { path = "../ospf-rust-base" }
ospf-rust-math = { path = "../ospf-rust-math" }
ospf-rust-multiarray = { path = "../ospf-rust-multiarray" }
ospf-rust-quantities = { path = "../ospf-rust-quantities" }
ospf-rust-core = { path = "../ospf-rust-core" }
ospf-rust-framework = { path = "../ospf-rust-framework" }

serde = { version = "1", features = ["derive"], optional = true }
thiserror = "1"
log = "0.4"
time = { version = "0.3", features = ["std", "macros"] }
rayon = { version = "1", optional = true }

[dev-dependencies]
ospf-rust-framework = { path = "../ospf-rust-framework" }
