#pragma once

#ifndef OSPF_PP_VARIADIC_MACRO
#define OSPF_PP_VARIADIC_MACRO

#define OSPF_MARCO_EXPAND(...)               __VA_ARGS__
#define OSPF_MACRO_CONCAT_IMPL(A_, B_)       A_##_##B_
#define OSPF_MACRO_CONCAT(A_, B_)            OSPF_MACRO_CONCAT_IMPL(A_, B_)

#define OSPF_MAKE_ARG_LIST_1(Op_, Arg_, ...)   Op_(Arg_)
#define OSPF_MAKE_ARG_LIST_2(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_1(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_3(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_2(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_4(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_3(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_5(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_4(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_6(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_5(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_7(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_6(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_8(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_7(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_9(Op_, Arg_, ...)   Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_8(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_10(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_9(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_11(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_10(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_12(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_11(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_13(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_12(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_14(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_13(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_15(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_14(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_16(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_15(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_17(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_16(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_18(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_17(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_19(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_18(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_20(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_19(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_21(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_20(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_22(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_21(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_23(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_22(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_24(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_23(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_25(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_24(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_26(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_25(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_27(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_26(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_28(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_27(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_29(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_28(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_30(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_29(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_31(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_30(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_32(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_31(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_33(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_32(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_34(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_33(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_35(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_34(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_36(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_35(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_37(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_36(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_38(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_37(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_39(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_38(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_40(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_39(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_41(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_40(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_42(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_41(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_43(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_42(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_44(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_43(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_45(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_44(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_46(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_45(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_47(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_46(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_48(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_47(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_49(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_48(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_50(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_49(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_51(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_50(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_52(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_51(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_53(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_52(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_54(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_53(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_55(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_54(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_56(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_55(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_57(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_56(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_58(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_57(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_59(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_58(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_60(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_59(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_61(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_60(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_62(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_61(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_63(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_62(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_64(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_63(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_65(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_64(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_66(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_65(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_67(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_66(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_68(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_67(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_69(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_68(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_70(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_69(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_71(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_70(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_72(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_71(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_73(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_72(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_74(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_73(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_75(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_74(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_76(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_75(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_77(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_76(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_78(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_77(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_79(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_78(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_80(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_79(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_81(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_80(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_82(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_81(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_83(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_82(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_84(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_83(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_85(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_84(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_86(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_85(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_87(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_86(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_88(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_87(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_89(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_88(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_90(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_89(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_91(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_90(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_92(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_91(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_93(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_92(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_94(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_93(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_95(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_94(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_96(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_95(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_97(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_96(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_98(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_97(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_99(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_98(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_100(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_99(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_101(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_100(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_102(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_101(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_103(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_102(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_104(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_103(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_105(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_104(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_106(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_105(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_107(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_106(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_108(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_107(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_109(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_108(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_110(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_109(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_111(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_110(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_112(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_111(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_113(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_112(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_114(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_113(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_115(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_114(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_116(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_115(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_117(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_116(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_118(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_117(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_119(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_118(Op_, __VA_ARGS__))
#define OSPF_MAKE_ARG_LIST_120(Op_, Arg_, ...)  Op_(Arg_), OSPF_MARCO_EXPAND(OSPF_MAKE_ARG_LIST_119(Op_, __VA_ARGS__))

#define OSPF_RSEQ_N() \
         119,118,117,116,115,114,113,112,111,110,\
         109,108,107,106,105,104,103,102,101,100,\
         99,98,97,96,95,94,93,92,91,90, \
         89,88,87,86,85,84,83,82,81,80, \
         79,78,77,76,75,74,73,72,71,70, \
         69,68,67,66,65,64,63,62,61,60, \
         59,58,57,56,55,54,53,52,51,50, \
         49,48,47,46,45,44,43,42,41,40, \
         39,38,37,36,35,34,33,32,31,30, \
         29,28,27,26,25,24,23,22,21,20, \
         19,18,17,16,15,14,13,12,11,10, \
         9,8,7,6,5,4,3,2,1,0

#define OSPF_ARG_N(\
         _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, \
         _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, \
         _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, \
         _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
         _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, \
         _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, \
         _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, \
         _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, \
         _81, _82, _83, _84, _85, _86, _87, _88, _89, _90, \
         _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, \
         _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, \
         _111, _112, _113, _114, _115, _116, _117, _118, _119, N, ...) N

#define OSPF_GET_ARG_COUNT_INNER(...)    OSPF_MARCO_EXPAND(OSPF_ARG_N(__VA_ARGS__))
#define OSPF_GET_ARG_COUNT(...)          OSPF_GET_ARG_COUNT_INNER(__VA_ARGS__, OSPF_RSEQ_N())

#define OSPF_MAKE_ARG_LIST(N_, Op_, Arg_, ...) \
        OSPF_MARCO_EXPAND(OSPF_MACRO_CONCAT(OSPF_MAKE_ARG_LIST, N_)(Op_, Arg_, __VA_ARGS__))
#endif
