[package]
name = "ospf-rust-multiarray"
version = "0.1.0"
edition = "2024"
authors = ["fuookami <wfuookami@gmail.com>"]
description = "A multi-array utils for ospf-rust."
license = "MIT"

homepage = "https://github.com/fuookami/ospf-rust"
repository = "https://github.com/fuookami/ospf-rust"
readme = "../README.md"

[dependencies]
paste = "1.0.15"
cc-traits = { git = "https://github.com/fuookami/cc-traits" }
dyn-clone = "1.0.20"
num-traits = "0.2"

[dependencies.ospf-rust-base]
path = "../ospf-rust-base"
version = "0.1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "multiarray_bench"
harness = false
