[package]
name = "ospf-rust-math"
version = "0.1.0"
authors = ["fuookami <fuookami@163.com>"]
edition = "2021"
description = "A math utils for ospf-rust."
license = "Apache-2.0"

[dependencies]
paste = "*"
num = "*"
bigdecimal = "*"
chrono = "*"
strum = { version = "*", features = ["derive"] }

[dependencies.ospf-rust-base]
path = "../ospf-rust-base"
version = "0.1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
