//! Intermediate symbol traits.

use std::collections::{HashMap, HashSet};
use std::fmt::Debug;
use std::hash::{Hash, Hasher};
use std::sync::{
    Arc,
    atomic::{AtomicU64, Ordering},
};

use ospf_rust_math::symbol::Symbol;

use crate::error::Result;
use crate::model::{
    LinearConstraint, QuadraticConstraint, RangeCacheContextTrait, RangeCacheKey,
    ValueCacheContextTrait, ValueCacheKey,
};
use crate::token::{Token, TokenList};
use crate::variable::VariableRange;

const AUTO_INTERMEDIATE_SYMBOL_ID_START: u64 = 1_000_000_000;

static NEXT_AUTO_INTERMEDIATE_SYMBOL_ID: AtomicU64 =
    AtomicU64::new(AUTO_INTERMEDIATE_SYMBOL_ID_START);

/// 生成自动中间符号 ID，使用较高命名空间以降低与显式 ID 冲突的概率。
/// Generate an auto intermediate symbol id from a high namespace to reduce collision risk with explicit ids.
pub fn next_auto_intermediate_symbol_id() -> u64 {
    NEXT_AUTO_INTERMEDIATE_SYMBOL_ID.fetch_add(1, Ordering::Relaxed)
}

/// 生成自动中间符号名称，保持名称可读并包含唯一 ID。
/// Generate a readable auto intermediate symbol name that includes the unique id.
pub(crate) fn auto_intermediate_symbol_name(prefix: &str, id: u64) -> String {
    format!("{}_{}", prefix, id)
}

/// Unique identifier for intermediate symbols.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct IntermediateSymbolId {
    pub id: u64,
    pub name: String,
}

impl IntermediateSymbolId {
    pub fn new(id: u64, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
        }
    }

    pub fn from_id(id: u64) -> Self {
        Self {
            id,
            name: format!("sym_{}", id),
        }
    }
}

/// Symbol category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    Linear,
    Quadratic,
    Polynomial,
    Nonlinear,
}

/// Value-evaluation context for intermediate symbols.
pub struct IntermediateSymbolEvalContext<'a, V>
where
    V: Clone + Debug + Send + Sync + 'static,
{
    pub values: &'a HashMap<usize, V>,
    pub cache: &'a mut dyn ValueCacheContextTrait<V>,
}

impl<'a, V> IntermediateSymbolEvalContext<'a, V>
where
    V: Clone + Debug + Send + Sync + 'static,
{
    pub fn new(
        values: &'a HashMap<usize, V>,
        cache: &'a mut dyn ValueCacheContextTrait<V>,
    ) -> Self {
        Self { values, cache }
    }
}

/// Range-inference context for intermediate symbols.
pub struct IntermediateSymbolRangeContext<'a, V>
where
    V: Clone + Debug + Send + Sync + 'static,
{
    pub cache: &'a mut dyn RangeCacheContextTrait<V>,
}

impl<'a, V> IntermediateSymbolRangeContext<'a, V>
where
    V: Clone + Debug + Send + Sync + 'static,
{
    pub fn new(cache: &'a mut dyn RangeCacheContextTrait<V>) -> Self {
        Self { cache }
    }
}

/// Core intermediate symbol trait.
pub trait IntermediateSymbol<V = f64>: Symbol<Id = IntermediateSymbolId> + Send + Sync
where
    V: Clone + Debug + Send + Sync + 'static,
{
    fn category(&self) -> Category;

    fn operation_category(&self) -> Category {
        self.category()
    }

    fn cached(&self) -> bool;

    fn parent(&self) -> Option<&dyn IntermediateSymbol<V>> {
        None
    }

    fn dependencies(&self) -> HashSet<Arc<dyn IntermediateSymbol<V>>>;

    /// Optional declared dependency ids (model-level explicit dependency graph).
    ///
    /// Default is empty.
    fn declared_dependency_ids(&self) -> Vec<u64> {
        Vec::new()
    }

    fn flush(&self, force: bool);

    /// Register auxiliary tokens (for function symbols).
    ///
    /// Default implementation does nothing.
    fn register_auxiliary_tokens(&self, _tokens: &mut Vec<Token<V>>) -> Result<()> {
        Ok(())
    }

    /// Build mechanism-layer linear constraints generated by this symbol.
    ///
    /// Default implementation emits no constraints.
    fn mechanism_constraints(
        &self,
        _symbol_to_index: &HashMap<usize, usize>,
    ) -> Result<Vec<LinearConstraint<V>>> {
        Ok(Vec::new())
    }

    /// Build mechanism-layer linear constraints with token context.
    ///
    /// The default implementation delegates to `mechanism_constraints`.
    fn mechanism_constraints_with_tokens(
        &self,
        symbol_to_index: &HashMap<usize, usize>,
        tokens: &[Token<V>],
    ) -> Result<Vec<LinearConstraint<V>>> {
        let _ = tokens;
        self.mechanism_constraints(symbol_to_index)
    }

    /// Build mechanism-layer quadratic constraints generated by this symbol.
    ///
    /// Default implementation emits no constraints.
    fn quadratic_mechanism_constraints(
        &self,
        _symbol_to_index: &HashMap<usize, usize>,
    ) -> Result<Vec<QuadraticConstraint<V>>> {
        Ok(Vec::new())
    }

    /// Build mechanism-layer quadratic constraints with token context.
    ///
    /// The default implementation delegates to `quadratic_mechanism_constraints`.
    fn quadratic_mechanism_constraints_with_tokens(
        &self,
        symbol_to_index: &HashMap<usize, usize>,
        tokens: &[Token<V>],
    ) -> Result<Vec<QuadraticConstraint<V>>> {
        let _ = tokens;
        self.quadratic_mechanism_constraints(symbol_to_index)
    }

    /// Evaluate symbol from token-table context (for function symbols).
    ///
    /// Default implementation returns `None` and falls back to `prepare(values)`.
    fn evaluate_from_tokens(
        &self,
        _token_table: &dyn TokenList<V>,
        _zero_if_none: bool,
    ) -> Option<V> {
        None
    }

    fn prepare(&self, values: &HashMap<usize, V>) -> Option<V>;

    fn evaluation_cache_key(&self) -> ValueCacheKey {
        ValueCacheKey::from_symbol(self.id().id)
    }

    /// Context-driven evaluation entry.
    ///
    /// Default implementation bridges to legacy `evaluate_with_ctx(values, cache)`.
    fn evaluate(&self, ctx: &mut IntermediateSymbolEvalContext<'_, V>) -> Option<V> {
        self.evaluate_with_ctx(ctx.values, ctx.cache)
    }

    fn evaluate_with_ctx(
        &self,
        values: &HashMap<usize, V>,
        ctx: &mut dyn ValueCacheContextTrait<V>,
    ) -> Option<V> {
        let key = self.evaluation_cache_key();
        if let Some(cached) = ctx.get(key) {
            return Some(cached.clone());
        }

        // Preheat dependency values before evaluating current symbol.
        let mut visited_dependency_ids = HashSet::new();
        let self_id = self.id().id;
        for dependency in self.dependencies() {
            let dependency_id = dependency.id().id;
            if dependency_id == self_id || !visited_dependency_ids.insert(dependency_id) {
                continue;
            }
            let _ = dependency.evaluate_with_ctx(values, ctx);
        }

        let value = self
            .evaluate_from_tokens(ctx.token_list(), false)
            .or_else(|| self.prepare(values));
        if let Some(v) = value.clone() {
            ctx.set(key, v);
        }
        value
    }

    fn range(&self) -> Option<VariableRange<V>> {
        None
    }

    fn range_cache_key(&self) -> RangeCacheKey {
        RangeCacheKey::from_symbol(self.id().id)
    }

    /// Context-driven range entry.
    ///
    /// Default implementation bridges to legacy `range_with_ctx(cache)`.
    fn range_in_context(
        &self,
        ctx: &mut IntermediateSymbolRangeContext<'_, V>,
    ) -> Option<VariableRange<V>> {
        self.range_with_ctx(ctx.cache)
    }

    fn range_with_ctx(&self, ctx: &mut dyn RangeCacheContextTrait<V>) -> Option<VariableRange<V>> {
        let key = self.range_cache_key();
        if let Some(cached) = ctx.get(key) {
            return Some(cached.clone());
        }

        let range = self.range();
        if let Some(r) = range.clone() {
            ctx.set(key, r);
        }
        range
    }

    fn to_raw_string(&self, unfold: u64) -> String;
}

impl<V> PartialEq for dyn IntermediateSymbol<V> + '_
where
    V: Clone + Debug + Send + Sync + 'static,
{
    fn eq(&self, other: &Self) -> bool {
        self.id().id == other.id().id
    }
}

impl<V> Eq for dyn IntermediateSymbol<V> + '_ where V: Clone + Debug + Send + Sync + 'static {}

impl<V> Hash for dyn IntermediateSymbol<V> + '_
where
    V: Clone + Debug + Send + Sync + 'static,
{
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.id().id.hash(state);
    }
}

/// Linear-symbol specialization.
pub trait LinearIntermediateSymbol<V = f64>: IntermediateSymbol<V>
where
    V: Clone + Debug + Send + Sync + 'static,
{
    fn to_linear_polynomial(&self) -> crate::symbol::flatten::Linear<V>;

    fn to_quadratic_polynomial(&self) -> crate::symbol::flatten::Quadratic<V>;
}

/// Quadratic-symbol specialization.
pub trait QuadraticIntermediateSymbol<V = f64>: IntermediateSymbol<V>
where
    V: Clone + Debug + Send + Sync + 'static,
{
    fn to_quadratic_polynomial(&self) -> crate::symbol::flatten::Quadratic<V>;
}

#[cfg(test)]
mod tests {
    use std::any::Any;
    use std::fmt::{Display, Formatter};
    use std::sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    };

    use ospf_rust_math::symbol::{DynSymbol, SymbolDynId};

    use crate::model::LazyValueCacheContext;
    use crate::token::VecTokenList;

    use super::*;

    #[derive(Debug, Clone)]
    struct TestSymbol {
        id: IntermediateSymbolId,
        deps: Vec<Arc<dyn IntermediateSymbol>>,
        value: f64,
        eval_calls: Arc<AtomicUsize>,
    }

    impl TestSymbol {
        fn new(
            id: u64,
            name: &str,
            deps: Vec<Arc<dyn IntermediateSymbol>>,
            value: f64,
            eval_calls: Arc<AtomicUsize>,
        ) -> Self {
            Self {
                id: IntermediateSymbolId::new(id, name),
                deps,
                value,
                eval_calls,
            }
        }
    }

    impl Display for TestSymbol {
        fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}", self.id.name)
        }
    }

    impl DynSymbol for TestSymbol {
        fn name(&self) -> &str {
            &self.id.name
        }

        fn display_name(&self) -> &str {
            &self.id.name
        }

        fn dyn_id(&self) -> SymbolDynId<'_> {
            SymbolDynId::standalone(self.id.id as usize)
        }

        fn as_any(&self) -> &dyn Any {
            self
        }
    }

    impl Symbol for TestSymbol {
        type Id = IntermediateSymbolId;

        fn id(&self) -> Self::Id {
            self.id.clone()
        }
    }

    impl IntermediateSymbol for TestSymbol {
        fn category(&self) -> Category {
            Category::Linear
        }

        fn cached(&self) -> bool {
            false
        }

        fn dependencies(&self) -> HashSet<Arc<dyn IntermediateSymbol>> {
            self.deps.iter().cloned().collect()
        }

        fn flush(&self, _force: bool) {}

        fn evaluate_from_tokens(
            &self,
            _token_table: &dyn TokenList<f64>,
            _zero_if_none: bool,
        ) -> Option<f64> {
            self.eval_calls.fetch_add(1, Ordering::SeqCst);
            Some(self.value)
        }

        fn prepare(&self, _values: &HashMap<usize, f64>) -> Option<f64> {
            None
        }

        fn to_raw_string(&self, _unfold: u64) -> String {
            self.id.name.clone()
        }
    }

    #[test]
    fn evaluate_with_ctx_preheats_dependencies_once() {
        let dep_calls = Arc::new(AtomicUsize::new(0));
        let root_calls = Arc::new(AtomicUsize::new(0));

        let dependency: Arc<dyn IntermediateSymbol> =
            Arc::new(TestSymbol::new(1, "dep", vec![], 1.0, dep_calls.clone()));
        let root = TestSymbol::new(2, "root", vec![dependency], 2.0, root_calls.clone());

        let token_list = Arc::new(VecTokenList::<f64>::new());
        let mut cache = LazyValueCacheContext::<f64, VecTokenList<f64>>::new();
        cache.init(token_list);

        let values = HashMap::new();
        let mut ctx = IntermediateSymbolEvalContext::new(&values, &mut cache);

        let first = root.evaluate(&mut ctx);
        let second = root.evaluate(&mut ctx);

        assert_eq!(first, Some(2.0));
        assert_eq!(second, Some(2.0));
        assert_eq!(dep_calls.load(Ordering::SeqCst), 1);
        assert_eq!(root_calls.load(Ordering::SeqCst), 1);
    }
}
