//! Demo9 模块 / Demo9 module
use std::error::Error;

use ospf_rust_multiarray::{MultiArray, Shape};
use ospf_rust_core::model::{MetaModel, ObjectiveCategory};
use ospf_rust_core::symbol::{
    SymbolCombination, AbsFunction, LinearExpressionSymbol, flat_map1_indexed,
};
use ospf_rust_core::variable::{
    Integer, VariableCombination1D, VariableRange,
};

use super::common::{read_solution_value, solve_typed};

/// Settlement data structure
#[derive(Debug, Clone)]
struct Settlement {
    name: String,
    x: f64,
    y: f64,
}

impl Settlement {
    fn new(name: &str, x: f64, y: f64) -> Self {
        Self { name: name.to_string(), x, y }
    }
}

fn build_settlements() -> Vec<Settlement> {
    vec![
        Settlement::new("S0", 9.0, 2.0),
        Settlement::new("S1", 2.0, 1.0),
        Settlement::new("S2", 3.0, 8.0),
        Settlement::new("S3", 3.0, -2.0),
        Settlement::new("S4", 5.0, 9.0),
        Settlement::new("S5", 4.0, -2.0),
    ]
}

/// Facility location model using VariableCombination + SymbolCombination
///
/// Uses AbsFunction intermediate symbols for absolute value linearization:
/// - `dx_fn[i] = |x - settlement[i].x|`
/// - `dy_fn[i] = |y - settlement[i].y|`
///
/// Mechanism constraints (Big-M linearization) are auto-generated by AbsFunction.
struct LocationModel {
    x: VariableCombination1D<Integer>,
    y: VariableCombination1D<Integer>,
    x_idx: MultiArray<usize, Shape<1>>,
    y_idx: MultiArray<usize, Shape<1>>,
    /// AbsFunction symbols: dx_fn[i] = |x - settlement[i].x|
    dx_fn: SymbolCombination<f64, AbsFunction<f64>, Shape<1>>,
    /// AbsFunction symbols: dy_fn[i] = |y - settlement[i].y|
    dy_fn: SymbolCombination<f64, AbsFunction<f64>, Shape<1>>,
    /// 距离符号：dx + dy
    distance_expr: SymbolCombination<f64, LinearExpressionSymbol<f64>, Shape<1>>,
}

impl LocationModel {
    fn register(
        model: &mut MetaModel<f64>,
        settlements: &[Settlement],
    ) -> Result<Self, Box<dyn Error>> {
        let n = settlements.len();

        // Scalar decision variables with bounded range
        let x = VariableCombination1D::with_range_generator(
            Shape::new([1]), "x",
            |_, _| VariableRange::bounded(-100.0, 100.0),
        );
        let y = VariableCombination1D::with_range_generator(
            Shape::new([1]), "y",
            |_, _| VariableRange::bounded(-100.0, 100.0),
        );
        let x_idx = model.register_combination(&x)?;
        let y_idx = model.register_combination(&y)?;

        // Per-settlement absolute distance components via AbsFunction
        let dx_fn = SymbolCombination::new(
            Shape::new([n]), "dx",
            |i, _| {
                AbsFunction::named(
                    &format!("dx_{}", settlements[i].name),
                    ospf_rust_core::symbol::flatten::Linear::new(
                        vec![ospf_rust_core::symbol::flatten::LinearMonomial::new(1.0, x_idx[0])],
                        -settlements[i].x,
                    ),
                )
            },
        );
        model.add_symbol_combination(&dx_fn)?;

        let dy_fn = SymbolCombination::new(
            Shape::new([n]), "dy",
            |i, _| {
                AbsFunction::named(
                    &format!("dy_{}", settlements[i].name),
                    ospf_rust_core::symbol::flatten::Linear::new(
                        vec![ospf_rust_core::symbol::flatten::LinearMonomial::new(1.0, y_idx[0])],
                        -settlements[i].y,
                    ),
                )
            },
        );
        model.add_symbol_combination(&dy_fn)?;

        // Compute result variable indices from AbsFunction symbols
        let dx_fn_idx: Vec<usize> = (0..n)
            .map(|i| dx_fn.symbol_polynomial(i).monomials()[0].var_index())
            .collect();
        let dy_fn_idx: Vec<usize> = (0..n)
            .map(|i| dy_fn.symbol_polynomial(i).monomials()[0].var_index())
            .collect();

        // Objective symbol: each settlement contributes dx_i + dy_i
        let distance_expr = flat_map1_indexed("distance", settlements, |i, _settlement| {
            ospf_rust_core::symbol::flatten::Linear::new(
                vec![
                    ospf_rust_core::symbol::flatten::LinearMonomial::new(1.0, dx_fn_idx[i]),
                    ospf_rust_core::symbol::flatten::LinearMonomial::new(1.0, dy_fn_idx[i]),
                ],
                0.0,
            )
        }, |_, settlement| settlement.name.clone());
        model.add_symbol_combination(&distance_expr)?;

        Ok(LocationModel {
            x, y, x_idx, y_idx,
            dx_fn, dy_fn,
            distance_expr,
        })
    }

    fn add_constraints(
        &self,
        model: &mut MetaModel<f64>,
        settlements: &[Settlement],
    ) -> Result<(), Box<dyn Error>> {
        // Aggregate objective: sum of all distance contributions
        let mut obj_monomials = Vec::new();
        for i in 0..settlements.len() {
            let poly = self.distance_expr.symbol_polynomial(i);
            for m in poly.monomials() {
                obj_monomials.push((m.var_index(), *m.coefficient()));
            }
        }
        model.add_linear_objective(&obj_monomials, "distance");
        model.set_objective_category(ObjectiveCategory::Minimum);

        // AbsFunction mechanism constraints (Big-M linearization for |x - sx|, |y - sy|)
        // are auto-generated during model conversion. No hand-written constraints needed.

        Ok(())
    }
}

/// Demo9 main function: Facility location problem (Manhattan distance)
pub fn run() -> Result<(), Box<dyn Error>> {
    let settlements = build_settlements();

    let mut model = MetaModel::<f64>::new("demo9");
    let loc = LocationModel::register(&mut model, &settlements)?;
    loc.add_constraints(&mut model, &settlements)?;

    let output = solve_typed(model)?;
    let solution = output.solution;

    println!("=== Demo9 ===");
    println!("status: {:?}", output.status);
    if let Some(obj) = output.objective_value {
        println!("distance sum: {:.2}", obj);
    }
    println!(
        "position: ({:.2}, {:.2})",
        read_solution_value(&solution, loc.x_idx[0]),
        read_solution_value(&solution, loc.y_idx[0])
    );
    for (i, settlement) in settlements.iter().enumerate() {
        let dx_result_idx = loc.dx_fn.symbol_polynomial(i).monomials()[0].var_index();
        let dy_result_idx = loc.dy_fn.symbol_polynomial(i).monomials()[0].var_index();
        println!(
            "{} ({:.2},{:.2}) distance components ({:.2},{:.2})",
            settlement.name,
            settlement.x,
            settlement.y,
            read_solution_value(&solution, dx_result_idx),
            read_solution_value(&solution, dy_result_idx)
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_demo9() {
        assert!(run().is_ok());
    }
}
